### ISSUE TITLE
Types is mandatory and not documented

### ISSUE THREAD

**Issue by devdigital** [leonardoanalista/cz-customizable#105]
Hi, great library, thanks. The config `types` appear to be mandatory, and are not documented. Without `types` specified, I get the following exception from `inquirer`:

```
(node:15496) UnhandledPromiseRejectionWarning: Error: You must provide a `choices` parameter
    at ListPrompt.throwParamError (/Users/LovellI/source/prosejs/node_modules/inquirer/lib/prompts/base.js:73:11)
    at new ListPrompt (/Users/LovellI/source/prosejs/node_modules/inquirer/lib/prompts/list.js:21:12)
    at PromptUI.fetchAnswer (/Users/LovellI/source/prosejs/node_modules/inquirer/lib/ui/prompt.js:85:25)
    at MergeMapSubscriber._tryNext (/Users/LovellI/source/prosejs/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
```

Suggest that some types are provided by default, or better error message, and README updated.

**Comment by leonardoanalista** [comment]
@no-creative-name do you still need this feature?
