### ISSUE TITLE
Unable to find configuration file.

### ISSUE THREAD

**Issue by brandondurham** [leonardoanalista/cz-customizable#39]
I’ve gone with the local install of commitizen for my project. It runs fine when I use the pure version, but when installing and implementing cz-customizable I get error messages regarding my configuration file.

```
cz-cli@2.9.6, cz-customizable@5.0.0

warn: Unable to find a configuration file. Please refer to documentation to learn how to ser up: https://github.com/leonardoanalista/cz-customizable#steps "
info:

Line 1 will be cropped at 100 characters. All other lines will be wrapped after 100 characters.

/Users/durham/Sites/hco-web-frontend/node_modules/cz-customizable/questions.js:17
    config.scopeOverrides = config.scopeOverrides || {};
                                  ^

TypeError: Cannot read property 'scopeOverrides' of undefined
    at Object.getQuestions (/Users/durham/Sites/hco-web-frontend/node_modules/cz-customizable/questions.js:17:35)
    at prompter (/Users/durham/Sites/hco-web-frontend/node_modules/cz-customizable/index.js:42:44)
    at /Users/durham/Sites/hco-web-frontend/node_modules/commitizen/dist/commitizen/commit.js:73:9
    at /Users/durham/Sites/hco-web-frontend/node_modules/commitizen/node_modules/fs-extra/lib/mkdirs/mkdirs.js:54:16
    at FSReqWrap.oncomplete (fs.js:123:15)
error Command failed with exit code 1.
```

I pasted the example config from this project into my project:

```
module.exports = {
	types: [
		{ value: 'feat', name: 'feat: A new feature' },
		{ value: 'fix', name: 'fix: A bug fix' },
		{ value: 'docs', name: 'docs: Documentation only changes' },
		{ value: 'style', name: 'style: Changes that do not affect the meaning of the code\n (white-space, formatting, missing semi-colons, etc)' },
		{ value: 'refactor', name: 'refactor: A code change that neither fixes a bug nor adds a feature' },
		{ value: 'perf', name: 'perf: A code change that improves performance' },
		{ value: 'test', name: 'test: Adding missing tests' },
		{ value: 'chore', name: 'chore: Changes to the build process or auxiliary tools\n and libraries such as documentation generation' },
		{ value: 'revert', name: 'revert: Revert to a commit' },
		{ value: 'WIP', name: 'WIP:  Work in progress' }
	],

	scopes: [
		{ name: 'accounts' },
		{ name: 'admin' },
		{ name: 'exampleScope' },
		{ name: 'changeMe' }
	],

	// it needs to match the value for field type. Eg.: 'fix'
	/*
	scopeOverrides: {
		fix: [
			{ name: 'merge' },
			{ name: 'style' },
			{ name: 'e2eTest' },
			{ name: 'unitTest' }
		]
	},
	*/
	allowCustomScopes: true,
	allowBreakingChanges: ['feat', 'fix']
};
```

This is located in an `internals` directory just inside the root of the project.

then this is the config in my `package.json` file:

```
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-customizable"
    }
  },
  "cz-customizable": {
    "config": "./internals/cz-config.js"
  }
```

Is there anything I’m doing wrong?

**Comment by leonardoanalista** [comment]
Easy one: nove the cuz-customizable block inside config property. Like this:

config": {
  "commitizen": {
    "path": "node_modules/cz-customizable"
  },
  "cz-customizable": {
    "config": "config/path/to/my/config.js"
  }

Cheers 
Leonardo

**Comment by brandondurham** [comment]
Silly mistake. Thank you!
